# Generated by Django 3.2 on 2021-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='ツイート')),
            ],
            options={
                'verbose_name_plural': 'Twitter',
            },
        ),
    ]
