# Generated by Django 3.2 on 2021-05-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twitter',
            new_name='Tweet',
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name_plural': 'Tweet'},
        ),
    ]
