# Generated by Django 3.2 on 2021-05-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210504_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twitter.tweet', verbose_name='ツイート')),
            ],
            options={
                'verbose_name_plural': 'Like',
            },
        ),
    ]
